### PR TITLE
Fix post types

### LINKED ISSUE #19: offered showing up in needed
I entered a offered post, and its showing up on on the needed filter too. Its showing up in both places.

screen shot 2015-11-04 at 11 33 12 am

### PR DESCRIPTION
**Pull request by cllns**
Fixes #19.

The issue was we were submitting the _value_ of the `post_type` enum, rather than the _key_, and changing the form params from string to integers. Rails handles the magic for us. :train: :gem:  :crystal_ball:

This also helps clean up some code: net **-4** lines of code, though I added two spec cases :D

### CODE REVIEW

File: app/controllers/posts_controller.rb [hunk 1]
```diff
@@ -8,7 +8,7 @@ def index
   end
 
   def new
-    @post = Post.new
+    @post = Post.new(post_type: "needed")
```
Comment (mi-wood) [inline app/controllers/posts_controller.rb]: does this need a default?

**Comment by mi-wood** [comment]
lgtm :hamster: :hamburger: thanks!

File: app/controllers/posts_controller.rb (hunk 1 above)
Comment (cllns) [inline app/controllers/posts_controller.rb]: If we want one of the radio buttons pre-checked, yes. Since FormBuilder calls `@post.post_type`, to figure out which should be checked by default.
